DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS fattura;
DROP TABLE IF EXISTS bene;
DROP TABLE IF EXISTS ddt;
DROP TABLE IF EXISTS azienda;
commit;
CREATE TABLE azienda (
     id int NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY(START WITH 4 INCREMENT BY 1),
     p_iva varchar(11) NOT NULL UNIQUE,
     cod_fis varchar(16) NOT NULL UNIQUE,
     nome varchar(50) NOT NULL,
     via varchar(60) DEFAULT NULL,
     civico varchar(10) DEFAULT NULL,
     cap varchar(6) DEFAULT NULL,
     citta varchar(50) DEFAULT NULL,
     provincia varchar(50) DEFAULT NULL,
     nazione varchar(50) DEFAULT NULL,
     telefono varchar(20) DEFAULT NULL,
     fax varchar(20) DEFAULT NULL,
     email varchar(50) DEFAULT NULL,
     principale varchar(1) DEFAULT 'N' NOT NULL,
     tassabile varchar(1) DEFAULT 'Y' NOT NULL,
     num_prot varchar(45) DEFAULT NULL,
     data_prot date DEFAULT NULL,
     pec varchar(50) DEFAULT NULL,
     codice_fattura_pa varchar(7) DEFAULT NULL
);
CREATE TABLE ddt (
     real_id int NOT NULL PRIMARY KEY IDENTITY,
     data date NOT NULL,
     id int NOT NULL,
     cliente int NOT NULL,
     mezzo varchar(12) DEFAULT NULL,
     causale varchar(45) DEFAULT NULL,
     destinazione varchar(255) DEFAULT NULL,
     vostro_ordine varchar(255) DEFAULT NULL,
     vostro_ordine_del varchar(255) DEFAULT NULL,
     tipo varchar(45) DEFAULT NULL,
     aspetto_esteriore varchar(45) DEFAULT NULL,
     colli int DEFAULT NULL,
     peso double DEFAULT NULL,
     porto varchar(45) DEFAULT NULL,
     ritiro varchar(255) DEFAULT NULL,
     annotazioni varchar(250) DEFAULT NULL,
     progressivo int DEFAULT NULL,
     fatturabile varchar(1) DEFAULT 'Y',
     fattura int DEFAULT NULL,
     idx int DEFAULT NULL,
     CONSTRAINT ddt_ibfk_1 FOREIGN KEY (cliente) REFERENCES azienda (id) ON DELETE NO ACTION ON UPDATE CASCADE
);
CREATE TABLE bene (
      id int NOT NULL PRIMARY KEY IDENTITY,
      ddt int NOT NULL,
      cod varchar(255) DEFAULT NULL,
      commessa varchar(50) DEFAULT NULL,
      descrizione varchar(50) NOT NULL,
      quantita float NOT NULL,
      prezzo float DEFAULT NULL,
      tot float DEFAULT NULL,
      prototipo varchar(1) DEFAULT 'N' NOT NULL,
      campionario varchar(1) DEFAULT 'N' NOT NULL,
      primo_capo varchar(1) DEFAULT 'N' NOT NULL,
      piazzato varchar(1) DEFAULT 'N' NOT NULL,
      adesivato varchar(1) DEFAULT 'N' NOT NULL,
      idx int NOT NULL,
      CONSTRAINT FK_bene_1 FOREIGN KEY (ddt) REFERENCES ddt (real_id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE fattura (
     real_id int NOT NULL PRIMARY KEY IDENTITY,
     id int NOT NULL,
     emissione date NOT NULL,
     scadenza date NOT NULL,
     cliente int NOT NULL,
     netto float NOT NULL,
     iva_perc float NOT NULL,
     iva float NOT NULL,
     totale float NOT NULL,
     bollo varchar(45) DEFAULT NULL,
     CONSTRAINT fattura_ibfk_1 FOREIGN KEY (cliente) REFERENCES azienda (id) ON DELETE NO ACTION ON UPDATE CASCADE
);
CREATE TABLE account (
     id int NOT NULL PRIMARY KEY IDENTITY,
     username varchar(50) NOT NULL,
     password varchar(50) NOT NULL,
     smtp varchar(50) NOT NULL
);
commit;


INSERT INTO azienda (id,p_iva,cod_fis,nome,via,civico,cap,citta,provincia,nazione,telefono,fax,email,principale)
VALUES
    (1,'01234567890','BRRVCN88M20G482K','CRTaglio','via A.Volta','1','65129','Pescara','PE','Italia','0854322029','0854322029','vinci.88@tiscali.it','Y');
commit;